papers_1995 <- "Dannegger, Felix; Klinger, Artur and Ulm, Kurt (1995): Identification of Prognostic Factors with Censored Data. Collaborative Research Center 386, Discussion Paper 11 [PDF, 409kB]
Fahrmeir, Ludwig; Gieger, Christian and Klinger, Artur (1995): Additive, Dynamic and Multiplicative Regression. Collaborative Research Center 386, Discussion Paper 1 [PDF, 812kB]
Fahrmeir, Ludwig and Klinger, Artur (1995): A nonparametric multiplicative hazard model for event history analysis. Collaborative Research Center 386, Discussion Paper 12 [PDF, 384kB]
Fahrmeir, Ludwig and Pritscher, L. (1995): Regression analysis of forest damage by marginal models for correlated ordinal responses. Collaborative Research Center 386, Discussion Paper 9 [PDF, 350kB]
Fahrmeir, Ludwig and Wagenpfeil, Stefan (1995): Smoothing Hazard Functions and Time-Varying Effects in Discrete Duration and Competing Risks Models. Collaborative Research Center 386, Discussion Paper 7 [PDF, 548kB]
Fahrmeir, Ludwig and Wagenpfeil, Stefan (1995): Penalized likelihood estimation and iterative kalman smoothing for non-gaussian dynamic regression models. Collaborative Research Center 386, Discussion Paper 5 [PDF, 694kB]
Knorr-Held, Leonhard (1995): Markov Chain Monte Carlo Simulation in Dynamic Generalized Linear Mixed Models. Collaborative Research Center 386, Discussion Paper 8 [PDF, 1MB]
Knorr-Held, Leonhard (1995): Dynamic Cumulative Probit Models for Ordinal Panel-Data; a Bayesian Analysis by Gibbs Sampling. Collaborative Research Center 386, Discussion Paper 2 [PDF, 651kB]
Küchenhoff, Helmut and Thamerus, Markus (1995): Extreme value analysis of Munich airpollution data. Collaborative Research Center 386, Discussion Paper 4 [PDF, 433kB]
Pruscha, Helmut (1995): Some Forecast Methods in Regression Models for Categorical Time Series. Collaborative Research Center 386, Discussion Paper 3 [PDF, 249kB]
Spiess, M. and Hamerle, Alfred (1995): Regression Models with Correlated Binary Response Variables: A Comparison of Different Methods in Finite Samples. Collaborative Research Center 386, Discussion Paper 10 [PDF, 375kB]
Wagenpfeil, Stefan (1995): Hyperparameter Estimation in Exponential Family State Space Models. Collaborative Research Center 386, Discussion Paper 6 [PDF, 335kB]"

papers_1996 <- "Aydemir, Sibel; Aydemir, Ülker and Dirschedl, Peter (1996): Survivalanalysen mit Berücksichtigung der zeitlichen Kovariablenentwicklung in klinischen Studien. Collaborative Research Center 386, Discussion Paper 44 [PDF, 431kB]
Aydemir, Sibel; Aydemir, Ülker and Dirschedl, Peter (1996): Das lineare Regressionsmodell von Aalen zur Analyse von Überlebenszeiten unter Berücksichtigung zeitveränderlicher Kovariablen. Collaborative Research Center 386, Discussion Paper 25 [PDF, 257kB]
Biller, Clemens and Fahrmeir, Ludwig (1996): Bayesian spline-type smoothing in generalized regression models. Collaborative Research Center 386, Discussion Paper 31 [PDF, 855kB]
Czado, Claudia (1996): Multivariate Probit Analysis of Binary Time Series Data with Missing Responses. Collaborative Research Center 386, Discussion Paper 23 [PDF, 306kB]
Czado, Claudia and Munk, Axel (1996): Noncanonical Links in Generalized Linear Models - When is the Effort Justified?. Collaborative Research Center 386, Discussion Paper 22 [PDF, 397kB]
Daumer, Martin; Falk, M. and Beyer, U. (1996): On-line monitoring using Multi-Process Kalman Filtering. Collaborative Research Center 386, Discussion Paper 54 [PDF, 261kB]
Fahrmeir, Ludwig and Knorr-Held, Leonhard (1996): Dynamic discrete-time duration models. (REVISED). Collaborative Research Center 386, Discussion Paper 14 [PDF, 460kB]
Fieger, A.; Heumann, Christian and Kastner, C. (1996): MAREG and WinMAREG. Collaborative Research Center 386, Discussion Paper 45 [PDF, 309kB]
Geil, Peter and Rotte, Ralph (1996): International Interventionism 1970-1989: A Count Data Approach. Collaborative Research Center 386, Discussion Paper 21 [PDF, 213kB]
Hamerle, Alfred and Moller, M. (1996): Semiparametric EM-estimation of censored linear regression models for durations. Collaborative Research Center 386, Discussion Paper 15 [PDF, 235kB]
Heumann, Christian (1996): Marginal regression modeling of correlated multicategorical response: A likelihood approach. Collaborative Research Center 386, Discussion Paper 19 [PDF, 366kB]
Hornsteiner, U. and Hamerle, Alfred (1996): A Combined GEE/Buckley-James Method for Estimating an Accelerated Failure Time Model of Multivariate Failure Times. Collaborative Research Center 386, Discussion Paper 47 [PDF, 408kB]
Johansson, P. and Brännäs, K. (1996): A Household Model for Work Absence. Collaborative Research Center 386, Discussion Paper 41
Knorr-Held, Leonhard (1996): Conditional Prior Proposals in Dynamic Models. Collaborative Research Center 386, Discussion Paper 36 [PDF, 443kB]
Küchenhoff, Helmut (1996): An exact algorithm for estimating breakpoints in segmented generalized linear models. Collaborative Research Center 386, Discussion Paper 27 [PDF, 240kB]
Pan, Guohua and Santner, Thomas J. (1996): Selection and Screening Procedures to Determine Optimal Product Designs. (REVISED, April 1997). Collaborative Research Center 386, Discussion Paper 52 [PDF, 390kB]
Pruscha, H. (1996): Residual and forecast methods in time series models with covariates. Collaborative Research Center 386, Discussion Paper 33 [PDF, 288kB]
Rieder, H. (1996): Estimation of Mortalities. Collaborative Research Center 386, Discussion Paper 28 [PDF, 429kB]
Santner, Thomas J. and Pan, Guohua (1996): The Use of Subset Selection in Combined Array Experiments to Determine Optimal Product or Process Designs. (REVISED, June 1997). Collaborative Research Center 386, Discussion Paper 51 [PDF, 293kB]
Schuster, G. (1996): ML-Estimation from Binomial Data with Misclassifications. A Comparison: Internal Validation versus Repeated Measurements. Collaborative Research Center 386, Discussion Paper 50
Schuster, G. (1996): ML-Estimation in a Case-Control Study with Measurement Error in the Risk Factor. A Comparison: External Validation versus Repeated Measurements. Collaborative Research Center 386, Discussion Paper 43
Schöpp, A. and Toutenburg, Helge (1996): Das symmetrische konditionale Regressionsmodell - alternative Parametrisierung bei korrelierten binären Responsevariablen. Collaborative Research Center 386, Discussion Paper 37 [PDF, 349kB]
Spiess, M. and Hamerle, Alfred (1996): Estimation of multivariate probit models: A mixed generalized estimating/pseudo-score equations approach and some finite sample results. Collaborative Research Center 386, Discussion Paper 46 [PDF, 355kB]
Spiess, M. and Hamerle, Alfred (1996): On the properties of GEE estimators in the presence of invariant covariates. Collaborative Research Center 386, Discussion Paper 13 [PDF, 257kB]
Stark, M.; Wagenpfeil, Stefan and Nekarda, H. (1996): Estimating Time-Varying Effects of Prognostic Factors for Stomach Cancer Patients within a Dynamic Grouped Cox Model. Collaborative Research Center 386, Discussion Paper 29 [PDF, 472kB]
Thamerus, Markus (1996): Fitting a Finite Mixture Distribution to a Variable Subject to Heteroscedastic Measurement Error. Collaborative Research Center 386, Discussion Paper 48 [PDF, 300kB]
Toutenburg, Helge; Srivastava, V. K. and Fieger, A. (1996): Estimation of Parameters in Multiple Regression With Missing X-Observations using Modified First Order Regression Procedure. Collaborative Research Center 386, Discussion Paper 38 [PDF, 253kB]
Ulm, Kurt; Dannegger, Felix and Spanier, M. (1996): Bericht über die Auswertung der Daten der Studie \"Chronische Bronchitis\". Collaborative Research Center 386, Discussion Paper 39 [PDF, 881kB]
Vach, W. and Illi, S. (1996): Biased Estimation of Adjusted Odds Ratios From Incomplete Covariate Data Due to Violation of the Missing at Random Assumption. Collaborative Research Center 386, Discussion Paper 17 [PDF, 288kB]
Veall, Michael R. and Zimmermann, Klaus F. (1996): Pseudo-R2 Measures for Some Common Limited Dependent Variable Models. Collaborative Research Center 386, Discussion Paper 18 [PDF, 246kB]
Wagenpfeil, Stefan (1996): Dynamische Modelle zur Ereignisanalyse. Collaborative Research Center 386, Discussion Paper 32 [PDF, 1MB]
Windmeijer, F. A. G. and Santos Silva, J. M. C. (1996): Estimation of count data models with endogenous regressors; an application to demand for health care. Collaborative Research Center 386, Discussion Paper 20 [PDF, 270kB]
Winkler, B. (1996): Bootstrapping Goodness of Fit Statistics in Loglinear Poisson Models. Collaborative Research Center 386, Discussion Paper 53 [PDF, 440kB]
Ziegler, Andreas; Kastner, C.; Grömping, U. and Blettner, Maria (1996): The Generalized Estimating Equations in the Past Ten Years: An Overview and A Biomedical Application. Collaborative Research Center 386, Discussion Paper 24 [PDF, 288kB]"

papers_1997 <- "Aydemir, Sibel and Biller, Clemens (1997): Kernel smoothing of Aalen's linear regression model. Collaborative Research Center 386, Discussion Paper 101 [PDF, 553kB]
Aydemir, Sibel and Hornsteiner, U. (1997): Analyse zeitveraenderlicher Kovariablen und rekurrenter Ereignisse am Beispiel einer Studie zur prophylaktischen Behandlung von Oesophagusvarizen. Collaborative Research Center 386, Discussion Paper 81 [PDF, 387kB]
Bauer, Thomas and Rotte, Ralph (1997): Prospect Theory Goes to War: Loss-Aversion and the Duration of Military Combat. Collaborative Research Center 386, Discussion Paper 97 [PDF, 208kB]
Bellmann, L.; Bender, S. and Hornsteiner, U. (1997): Interfirm Job Mobility of Two Cohorts of Young German Men 1979 - 1990: An analysis of the (West-)German Employment Statistic Register Sample concerning multivariate failure times and unobserved heterogeneity. Collaborative Research Center 386, Discussion Paper 94 [PDF, 167kB]
Biller, Clemens (1997): Discrete Duration Models combining Dynamic and Random Effects. (REVISED, February 2000). Collaborative Research Center 386, Discussion Paper 88 [PDF, 350kB]
Biller, Clemens (1997): Posterior mode estimation in dynamic generalized linear mixed models. (REVISED, June 2000). Collaborative Research Center 386, Discussion Paper 70 [PDF, 358kB]
Caputo, Angelika; Heinicke, A. and Pigeot, Iris (1997): A graphical chain model derived from a model selection strategy for the sociologists graduates study. Collaborative Research Center 386, Discussion Paper 73 [PDF, 351kB]
Cheng, Chi-Lun and Schneeweiß, Hans (1997): Note on Two Estimators for the Polynomial Regression with Errors in the Variables. Collaborative Research Center 386, Discussion Paper 96 [PDF, 216kB]
Dannegger, Felix (1997): Tree stability diagnostics and some remedies against instability. Collaborative Research Center 386, Discussion Paper 72 [PDF, 357kB]
Daumer, Martin; Bauer, C. and Lederer, C. (1997): Average Run Length and Mean Delay for Changepoint Detection: Robust Estimates for Threshold Alarms. Collaborative Research Center 386, Discussion Paper 95 [PDF, 241kB]
Didelez, V. and Pigeot, Iris (1997): Maximum Likelihood Estimation in Graphical Models with Missing Values. Collaborative Research Center 386, Discussion Paper 75 [PDF, 293kB]
Fahrmeir, Ludwig (1997): Discrete failure time models. Collaborative Research Center 386, Discussion Paper 91 [PDF, 220kB]
Fahrmeir, Ludwig; Gieger, Christian and Heumann, Christian (1997): An application of isotonic longitudinal marginal regression to monitoring the healing process. Collaborative Research Center 386, Discussion Paper 89 [PDF, 238kB]
Fahrmeir, Ludwig and Klinger, Artur (1997): A nonparametric multiplicative hazard model for event history analysis (strongly modified and revised version of Discussion Paper 12). Collaborative Research Center 386, Discussion Paper 12
Fahrmeir, Ludwig and Knorr-Held, Leonhard (1997): Dynamic and semiparametric models. Collaborative Research Center 386, Discussion Paper 76 [PDF, 404kB]
Fieger, A. (1997): Modified First Order Regression, eine Simulationsstudie. Collaborative Research Center 386, Discussion Paper 62 [PDF, 402kB]
Fieger, A. (1997): C++ Klassen zur Linearen Regression bei fehlenden Kovariablen. Collaborative Research Center 386, Discussion Paper 61 [PDF, 337kB]
Fieger, A.; Heumann, Christian; Kastner, C. and Watzka, K. (1997): Generische Bibliothek zur Linearen Algebra und zur Simulation in C++. Collaborative Research Center 386, Discussion Paper 63 [PDF, 347kB]
Gieger, Christian (1997): Non- and semiparametric marginal regression models for ordinal response. Collaborative Research Center 386, Discussion Paper 71 [PDF, 325kB]
Haybach, G. and Küchenhoff, Helmut (1997): Testing for a Breakpoint in Two-Phase Linear and Logistic Regression Models. Collaborative Research Center 386, Discussion Paper 77 [PDF, 527kB]
Hornsteiner, U.; Hamerle, Alfred and Michels, P. (1997): Parametric versus Nonparametric Treatment of Unobserved Heterogeneity in Multivariate Failure Times. Collaborative Research Center 386, Discussion Paper 80 [PDF, 346kB]
Kastner, C. and Ziegler, Andreas (1997): Cross-sectional Analysis of Longitudinal Data with Missing Values in the Dependent Variables: A Comparison of Weighted Estimating Equations with the Complete Case Analysis. Collaborative Research Center 386, Discussion Paper 64 [PDF, 291kB]
Klinger, Artur (1997): Generalized Soft-Thresholding and Varying-coefficient Models. Collaborative Research Center 386, Discussion Paper 59 [PDF, 598kB]
Knorr-Held, Leonhard (1997): Dynamic Rating of Sports Teams. (REVISED 1999). Collaborative Research Center 386, Discussion Paper 98 [PDF, 383kB]
Küchenhoff, Helmut and Wellisch, U. (1997): Asymptotics for generalized linear segmented regression models with an unknown breakpoint. Collaborative Research Center 386, Discussion Paper 83 [PDF, 315kB]
Luhm, A. and Pruscha, H. (1997): Semi-parametric Inference for Regression Models Based on Marked Point Processes. Collaborative Research Center 386, Discussion Paper 78 [PDF, 317kB]
Pan, Guohua and Santner, Thomas J. (1997): Screening Procedures to Identify Robust Product or Process Designs Using Fractional Factorial Experiments. Collaborative Research Center 386, Discussion Paper 92 [PDF, 346kB]
Pigeot, Iris; Heinicke, A.; Caputo, Angelika and Brüderl, Josef (1997): The professional career of sociologists: a graphical chain model reflecting early influences and associations. Collaborative Research Center 386, Discussion Paper 74 [PDF, 329kB]
Pruscha, H. (1997): Semiparametric Estimation in Regression Models for Point Processes based on One Realization. Collaborative Research Center 386, Discussion Paper 66 [PDF, 247kB]
Pruscha, H.; Ulm, Kurt and Schmidt, G. (1997): Statistische Analyse des Einflusses von Herzrhythmusstörungen auf das Mortalitätsrisiko. Collaborative Research Center 386, Discussion Paper 56 [PDF, 259kB]
Pruscha, H. and Wellisch, U. (1997): Asymptotic behaviour of estimation equations with functional nuisance or working parameter. Collaborative Research Center 386, Discussion Paper 79 [PDF, 283kB]
Santner, Thomas J. (1997): A Note on Teaching Binomial Confidence Intervals. Collaborative Research Center 386, Discussion Paper 87 [PDF, 212kB]
Schneeweiß, Hans (1997): Korrigierte Schaetzgleichungen fuer allgemeine Regressionsmodelle mit Fehlern in den Variablen. Collaborative Research Center 386, Discussion Paper 93 [PDF, 208kB]
Spatz, R. and Hamerle, Alfred (1997): Ein Mehr-Zustands-Mehr-Episoden-Modell in diskreter Zeit zur Analyse klinischer Studien unter Beruecksichtigung unbeobachteter Heterogenitaet. Collaborative Research Center 386, Discussion Paper 82 [PDF, 356kB]
Spiess, M.; Nagl, W. and Hamerle, Alfred (1997): Probit models: Regression parameter estimation using the ML principle despite misspecification of the correlation structure. Collaborative Research Center 386, Discussion Paper 67 [PDF, 411kB]
Stark, M. (1997): Zu Vorhersage und Vorhersagewert fuer Ueberlebenszeitmodelle. Collaborative Research Center 386, Discussion Paper 84 [PDF, 435kB]
Thamerus, Markus (1997): Different Nonlinear Regression Models with Incorrectly Observed Covariates. Collaborative Research Center 386, Discussion Paper 68 [PDF, 287kB]
Thamerus, Markus (1997): Modelling Count Data with Heteroscedastic Measurement Error in the Covariates. Collaborative Research Center 386, Discussion Paper 58 [PDF, 299kB]
Toutenburg, Helge; Srivastava, V. K. and Fieger, A. (1997): Shrinkage Estimation of Incomplete Regression Models by Yates Procedure. Collaborative Research Center 386, Discussion Paper 69 [PDF, 264kB]
Ziegler, Andreas; Blettner, Maria; Kastner, C. and Chang-Claude, J. (1997): Identifying Influential Families Using Regression Diagnostics For Generalized Estimating Equations. Collaborative Research Center 386, Discussion Paper 60
Ziegler, Andreas and Kastner, C. (1997): A Minimum Distance Estimation Approach to Estimate the Recombination Fraction from a Marker Locus in Robust Linkage Analysis for Quantitative Traits. Collaborative Research Center 386, Discussion Paper 65"

papers_1998 <- "Bauer, Thomas; Million, A.; Rotte, Ralph and Zimmermann, Klaus F. (1998): Immigrant Labor and Workplace Safety. Collaborative Research Center 386, Discussion Paper 117
Biller, Clemens (1998): Adaptive Bayesian Regression Splines in Semiparametric Generalized Linear Models. Collaborative Research Center 386, Discussion Paper 133 [PDF, 403kB]
Caputo, Angelika (1998): Decomposition of ML Estimation in Graphical Models with Koehler Symanowski distributions. Collaborative Research Center 386, Discussion Paper 105 [PDF, 360kB]
Caputo, Angelika (1998): Graphical models with Koehler Symanowski distributions. Collaborative Research Center 386, Discussion Paper 104 [PDF, 305kB]
Caputo, Angelika (1998): Some properties of the family of Koehler Symanowski distributions. Collaborative Research Center 386, Discussion Paper 103 [PDF, 362kB]
Cheng, Chi-Lun; Schneeweiß, Hans and Thamerus, Markus (1998): A Small Sample Estimator for a Polynomial Regression with Errors in the Variables. Collaborative Research Center 386, Discussion Paper 113 [PDF, 294kB]
Didelez, V. (1998): Maximum Likelihood and Semiparametric Estimation in Logistic Models with Incomplete Covariate Data. Collaborative Research Center 386, Discussion Paper 110 [PDF, 343kB]
Fahrmeir, Ludwig (1998): Recent Advances in Semiparametric Bayesian Function Estimation. Collaborative Research Center 386, Discussion Paper 137 [PDF, 280kB]
Fahrmeir, Ludwig and Künstler, R. (1998): Penalized likelihood smoothing in robust state space models. Collaborative Research Center 386, Discussion Paper 111 [PDF, 355kB]
Fahrmeir, Ludwig and Lang, S. (1998): Bayesian Inference for Generalized Additive Regression based on Dynamic Models. Collaborative Research Center 386, Discussion Paper 134 [PDF, 399kB]
Fieger, A.; Kastner, C. and Heumann, Christian (1998): WinMAREG Quick Start. Collaborative Research Center 386, Discussion Paper 108 [PDF, 292kB]
Fronk, Eva-Maria and Fahrmeir, Ludwig (1998): Function estimation with locally adaptive dynamic models. Collaborative Research Center 386, Discussion Paper 135 [PDF, 428kB]
Gössl, Christoff; Auer, Dorothee P. and Fahrmeir, Ludwig (1998): Dynamic models in fMRI. Collaborative Research Center 386, Discussion Paper 136 [PDF, 383kB]
Hahn, Klaus and Waschulzik, T. (1998): On the Use of Local RBF Networks to Approximate Multivalued Functions and Relations. Collaborative Research Center 386, Discussion Paper 116 [PDF, 403kB]
Heumann, Christian; Fieger, A. and Kastner, C. (1998): C++ Utilities zur Implementierung statistischer Verfahren unter Berücksichtigung fehlender Werte. Collaborative Research Center 386, Discussion Paper 109 [PDF, 281kB]
Knorr-Held, Leonhard and Rasser, G. (1998): Bayesian Detection of Clusters and Discontinuities in Disease Maps. (REVISED, February 1999). Collaborative Research Center 386, Discussion Paper 107 [PDF, 716kB]
Mayer, Jochen and Riphahn, Regina T. (1998): Fertility Assimilation of Immigrants: A Varying Coefficient Count Data Model. Collaborative Research Center 386, Discussion Paper 140 [PDF, 479kB]
Pigeot, Iris; Blauth, Angelika and Bry, François (1998): Interactive analysis of high-dimensional association structures with graphical models. Collaborative Research Center 386, Discussion Paper 131 [PDF, 326kB]
Pruscha, H. (1998): Semiparametric Point Process and Time Series Models for Series of Events. Collaborative Research Center 386, Discussion Paper 114 [PDF, 264kB]
Schaffrin, B. and Toutenburg, Helge (1998): The Impact of Missing Values on the Reliability Measures in a Linear Model. Collaborative Research Center 386, Discussion Paper 125 [PDF, 271kB]
Smith, Murray D. (1998): On Dependency in Double-Hurdle Models. Collaborative Research Center 386, Discussion Paper 139 [PDF, 1MB]
Smith, Murray D. and Moffatt, P. G. (1998): Fisher's Information on the Correlation Coefficient in Bivariate Models. Collaborative Research Center 386, Discussion Paper 126
Spiess, M. and Keller, F. (1998): A mixed approach and a distribution free multiple imputation technique for the estimation of multivariate probit models with missing values. Collaborative Research Center 386, Discussion Paper 102 [PDF, 386kB]
Toutenburg, Helge; Fieger, A. and Heumann, Christian (1998): Regression modelling with fixed effects - missing values and other problems. Collaborative Research Center 386, Discussion Paper 123 [PDF, 264kB]
Toutenburg, Helge; Fieger, A. and Srivastava, V. K. (1998): Weighted Modified First Order Regression Procedures for Estimation in Linear Models with Missing X-Observations. Collaborative Research Center 386, Discussion Paper 127 [PDF, 227kB]
Toutenburg, Helge and Shalabh (1998): Improved Predictions in Linear Regression Models with Stochastic Linear Constraints. Collaborative Research Center 386, Discussion Paper 124 [PDF, 270kB]
Toutenburg, Helge and Shalabh (1998): Use of minimum risk approach in the estimation of regression models with missing observation. Collaborative Research Center 386, Discussion Paper 118 [PDF, 199kB]
Toutenburg, Helge and Shalabh (1998): Prediction of Response Values in Linear Regression Models from Replicated Experiments. Collaborative Research Center 386, Discussion Paper 112 [PDF, 214kB]
Toutenburg, Helge and Srivastava, V. K. (1998): Impact of Departure from Normality on the Efficiency of Estimating Regression Coefficients when Some Observations are Missing. Collaborative Research Center 386, Discussion Paper 130 [PDF, 273kB]
Toutenburg, Helge and Srivastava, V. K. (1998): Improving the Estimation of Coefficients in Linear Regression Models with Some Missing Observations on Some Explanatory Variables. Collaborative Research Center 386, Discussion Paper 129 [PDF, 261kB]
Toutenburg, Helge and Srivastava, V. K. (1998): Estimation of Ratio of Population Means in Survey Sampling When Some Observations are Missing. Collaborative Research Center 386, Discussion Paper 119 [PDF, 181kB]
Toutenburg, Helge; Srivastava, V. K. and Schaffrin, B. (1998): Efficiency properties of weighted mixed regression estimation. Collaborative Research Center 386, Discussion Paper 122 [PDF, 262kB]
Ulm, Kurt; Dannegger, Felix and Becker, Ursula (1998): Tests for Trends in Binary Response. Collaborative Research Center 386, Discussion Paper 115 [PDF, 325kB]
Winkler, Gerhard (1998): Moment Sets of Bell-Shaped Distributions: Extreme Points, Extremal Decomposition and Chebysheff Inequalities. Collaborative Research Center 386, Discussion Paper 121 [PDF, 424kB]
Winkler, Gerhard (1998): An Adaptive Gradient Algorithm for Maximum Likelihood Estimation in Imaging. A Tutorial. Collaborative Research Center 386, Discussion Paper 120 [PDF, 414kB]
Winkler, Gerhard; Aurich, Volker; Hahn, Klaus; Martin, A. and Rodenacker, K. (1998): Noise Reduction in Images: Some Recent Edge-Preserving Methods. Collaborative Research Center 386, Discussion Paper 138 [PDF, 3MB]
Winkler, Gerhard; Hahn, Klaus and Aurich, Volker (1998): A Brief Survey of Recent Edge-Preserving Smoothers. Collaborative Research Center 386, Discussion Paper 132 [PDF, 351kB]
Ziegler, Andreas and Kastner, C. (1998): Solving Generalised Estimating Equations With Missing Data Using Pseudo Maximum Likelihood Estimation Is Equivalent to Complete Case Analysis. Collaborative Research Center 386, Discussion Paper 128 [PDF, 242kB]"

papers_1999 <- "Augustin, Thomas (1999): Neyman-Pearson Testing under Interval Probability by Globally Least Favorable Pairs: A Survey of Huber-Strassen Theory and Some Results on its Extension to General Interval Probability. Collaborative Research Center 386, Discussion Paper 172 [PDF, 404kB]
Augustin, Thomas (1999): Correcting for measurement error in parametric duration models by quasi-likelihood. Collaborative Research Center 386, Discussion Paper 157 [PDF, 429kB]
Caputo, Angelika (1999): Factorization of the Cumulative Distribution Function in Case of Conditional Independence. (REVISED, November 1999). Collaborative Research Center 386, Discussion Paper 161 [PDF, 298kB]
Didelez, V. (1999): Local independence graphs for composable Markov processes. Collaborative Research Center 386, Discussion Paper 158 [PDF, 345kB]
Dreesman, J. and Tutz, Gerhard (1999): Nonstationary conditional models for spatial data based on varying coefficients. Collaborative Research Center 386, Discussion Paper 150 [PDF, 287kB]
Eberle, W. and Toutenburg, Helge (1999): Handling of missing values in statistical software packages for windows. Collaborative Research Center 386, Discussion Paper 170 [PDF, 336kB]
Fahrmeir, Ludwig and Lang, S. (1999): Bayesian Inference for Generalized Additive Mixed Models Based on Markov Random Field Priors. Collaborative Research Center 386, Discussion Paper 134
Friedl, H. and Kauermann, Göran (1999): Standard Errors for EM Estimates in Variance Component Models. Collaborative Research Center 386, Discussion Paper 145 [PDF, 285kB]
Gieger, Christian (1999): Marginal Regression Models with Varying Coefficients for Correlated Ordinal Data. Collaborative Research Center 386, Discussion Paper 177 [PDF, 339kB]
Giudici, P.; Knorr-Held, Leonhard and Rasser, G. (1999): Modelling categorical covariates in Bayesian disease mapping by partition structures. Collaborative Research Center 386, Discussion Paper 152 [PDF, 816kB]
Gössl, Christoff and Küchenhoff, Helmut (1999): Bayesian analysis of logistic regression with an unknown change point. Collaborative Research Center 386, Discussion Paper 148 [PDF, 559kB]
Kastner, C.; Fieger, A. and Heumann, Christian (1999): New features in MAREG 0.2.0. Collaborative Research Center 386, Discussion Paper 156 [PDF, 282kB]
Kastner, C. and Ziegler, Andreas (1999): A Comparison of Jackknife Estimators of Variance for GEE2. Collaborative Research Center 386, Discussion Paper 167 [PDF, 257kB]
Kauermann, Göran (1999): On a Small Sample Adjustment for the Profile Score Function in Semiparametric Smoothing Models. Collaborative Research Center 386, Discussion Paper 162 [PDF, 300kB]
Kauermann, Göran (1999): Modeling longitudinal data with ordinal response by varying coefficients. Collaborative Research Center 386, Discussion Paper 144 [PDF, 339kB]
Kauermann, Göran and Tutz, Gerhard (1999): Testing Generalized Linear and Semiparametric Models Against Smooth Alternatives. Collaborative Research Center 386, Discussion Paper 149 [PDF, 385kB]
Klinger, Artur (1999): Inference in High Dimensional Generalized Linear Models based on Soft-Thresholding. Collaborative Research Center 386, Discussion Paper 165 [PDF, 491kB]
Knorr-Held, Leonhard (1999): Bayesian Modelling of Inseparable Space-Time Variation in Disease Risk. Collaborative Research Center 386, Discussion Paper 147 [PDF, 712kB]
Knorr-Held, Leonhard and Becker, Nikolaus (1999): Bayesian Modelling of Spatial Heterogeneity in Disease Maps with Application to German Cancer Mortality Data. Collaborative Research Center 386, Discussion Paper 176 [PDF, 931kB]
Knorr-Held, Leonhard and Rainer, E. (1999): Prognosis of Lung Cancer Mortality in West Germany: A Case Study in Bayesian Prediction. (REVISED, January 2000). Collaborative Research Center 386, Discussion Paper 160 [PDF, 444kB]
Knorr-Held, Leonhard and Rasser, G. (1999): Bayesian Detection of Clusters and Discontinuities in Disease Maps: Simulations. (REVISED, June 1999). Collaborative Research Center 386, Discussion Paper 142 [PDF, 1MB]
Nikele, M. and Fahrmeir, Ludwig (1999): A latent variable probit model for multivariate ordered categorical responses. Collaborative Research Center 386, Discussion Paper 164 [PDF, 785kB]
Pruscha, H. and Göttlein, A. (1999): Regression Analysis for Forest Inventory Data with Time and Space Dependencies. Collaborative Research Center 386, Discussion Paper 173 [PDF, 340kB]
Rose, Colin and Smith, Murray D. (1999): Symbolic Maximum Likelihood Estimation with Mathematica. Collaborative Research Center 386, Discussion Paper 141 [PDF, 223kB]
Schneeweiß, Hans (1999): Resolving the Ellsberg Paradox by Assuming that People Evaluate Repetitive Sampling. Collaborative Research Center 386, Discussion Paper 153 [PDF, 242kB]
Shao, J.; Kübler, J. and Pigeot, Iris (1999): Consistency of the Bootstrap Procedure in Individual Bioequivalence. Collaborative Research Center 386, Discussion Paper 159 [PDF, 296kB]
Srivastava, V. K. and Toutenburg, Helge (1999): On the First Order Regression Procedure of Estimation for Incomplete Regression Models. Collaborative Research Center 386, Discussion Paper 175 [PDF, 201kB]
Toutenburg, Helge; Fieger, A. and Schaffrin, B. (1999): Approximate Confidence Regions for Minimax-Linear Estimators. Collaborative Research Center 386, Discussion Paper 166 [PDF, 295kB]
Toutenburg, Helge and Nittner, T. (1999): The Classical Linear Regression Model with one Incomplete Binary Variable. Collaborative Research Center 386, Discussion Paper 178 [PDF, 521kB]
Toutenburg, Helge and Shalabh (1999): Estimation of Regression Models with Equi-correlated Responses when some Observations on the Response Variable are Missing. Collaborative Research Center 386, Discussion Paper 174 [PDF, 243kB]
Toutenburg, Helge and Shalabh (1999): Estimation of Regression Coefficients Subject to Exact Linear Restrictions when some Observations are Missing and Balanced Loss Function is Used. Collaborative Research Center 386, Discussion Paper 163 [PDF, 239kB]
Toutenburg, Helge and Shalabh (1999): Improving the Estimation of Incomplete Regression Models through Pilot Investigations and Repeated Studies. Collaborative Research Center 386, Discussion Paper 154 [PDF, 236kB]
Toutenburg, Helge and Srivastava, V. K. (1999): Amputation versus Imputation of Missing Values through Ratio Method in Sample Surveys. Collaborative Research Center 386, Discussion Paper 155 [PDF, 256kB]
Trevisani, M.; Causin, R.; Montecchio, L.; Kastner, C. and Heumann, Christian (1999): Analysing the relationship between ectomycorrhizal infection and forest decline using marginal models. Collaborative Research Center 386, Discussion Paper 143 [PDF, 359kB]
Tutz, Gerhard; Edlich, Silke and Bäumer, Christoph (1999): Comparison between local estimates for multi-categorical varying-coefficent models. Collaborative Research Center 386, Discussion Paper 151 [PDF, 299kB]
Winkler, Gerhard; Liebscher, V. and Aurich, Volker (1999): Smoothers for Discontinuous Signals. Collaborative Research Center 386, Discussion Paper 146 [PDF, 758kB]
Ziegler, Andreas; Kastner, C.; Brunner, D. and Blettner, Maria (1999): Familial Associations of Lipid Profiles: A Generalised Estimating Equations Approach. Collaborative Research Center 386, Discussion Paper 168 [PDF, 321kB]"

papers_2000 <- "Augustin, Thomas (2000): Some Basic Results on the Extension of Quasi-Likelihood Based Measurement Error Correction to Multivariate and Flexible Structural Models. Collaborative Research Center 386, Discussion Paper 196 [PDF, 290kB]
Berger, Ursula; Gerein, Pia; Ulm, Kurt and Schäfer, Juliane (2000): On the use of Fractional Polynomials in Dynamic Cox Models. Collaborative Research Center 386, Discussion Paper 207 [PDF, 356kB]
Blauth, A. and Pigeot, Iris (2000): GraphFitI - A computer program for graphical chain models. Collaborative Research Center 386, Discussion Paper 224 [PDF, 327kB]
Briegel, T. and Tresp, V. (2000): Dynamic Neural Regression Models. Collaborative Research Center 386, Discussion Paper 181 [PDF, 529kB]
Didelez, V.; Pigeot, Iris; Dean, K. and Wister, A. (2000): A comparative analysis of graphical interaction and logistic regression modelling: self-care and coping with a chronic illness in later life. Collaborative Research Center 386, Discussion Paper 186 [PDF, 348kB]
Didelez, V.; Pigeot, Iris and Walter, P. (2000): Modifications of the Bonferroni-Holm procedure for a multi-way ANOVA. Collaborative Research Center 386, Discussion Paper 185 [PDF, 334kB]
Fahrmeir, Ludwig and Lang, S. (2000): Bayesian Semiparametric Regression Analysis of Multicategorical Time-Space Data. Collaborative Research Center 386, Discussion Paper 202 [PDF, 633kB]
Fahrmeir, Ludwig; Lang, S.; Wolff, J. and Bender, S. (2000): Semiparametric Bayesian Time-Space Analysis of Unemployment Duration. Collaborative Research Center 386, Discussion Paper 211 [PDF, 828kB]
Fronk, Eva-Maria and Giudici, P. (2000): Markov Chain Monte Carlo Model Selection for DAG Models. Collaborative Research Center 386, Discussion Paper 221 [PDF, 345kB]
Galindo, C. D.; Kauermann, Göran; Liang, H. and Carroll, R. J. (2000): Bootstrap Confidence Intervals For Local Likelihood, Local Estimating Equations And Varying Coefficient Models. Collaborative Research Center 386, Discussion Paper 205 [PDF, 328kB]
Gartner, H. (2000): Die Ersetzung fehlender Werte: Ein Test alternativer Methoden mit Makrodaten. Collaborative Research Center 386, Discussion Paper 216 [PDF, 305kB]
Gartner, H. (2000): Das Auszugsverhalten junger Menschen aus dem Elternhaus in Westdeutschland seit 1984. Collaborative Research Center 386, Discussion Paper 215 [PDF, 365kB]
Gössl, Christoff; Auer, Dorothee P. and Fahrmeir, Ludwig (2000): Bayesian spatio-temporal inference in functional magnetic resonance imaging. Collaborative Research Center 386, Discussion Paper 192 [PDF, 648kB]
Hahn, Klaus; Rodenacker, K.; Aurich, Volker and Auer, Dorothee P. (2000): Segmentierung des Gehirns auf der Basis von MR-Daten. Collaborative Research Center 386, Discussion Paper 180 [PDF, 282kB]
Heumann, Christian (2000): Intention-to-treat with drop-out. Collaborative Research Center 386, Discussion Paper 199 [PDF, 287kB]
Kauermann, Göran and Carroll, R. J. (2000): The Sandwich Variance Estimator: Efficiency Properties and Coverage Probability of Confidence Intervals. Collaborative Research Center 386, Discussion Paper 189 [PDF, 370kB]
Kauermann, Göran and Opsomer, J. D. (2000): Local Likelihood Estimation in Generalized Additive Models. Collaborative Research Center 386, Discussion Paper 190 [PDF, 474kB]
Kauermann, Göran and Tutz, Gerhard (2000): Semiparametric Modeling of Ordinal Data. Collaborative Research Center 386, Discussion Paper 193 [PDF, 353kB]
Klasen, S. (2000): Malnourished and surviving in South Asia, better nourished and dying young in Africa: What can explain this puzzle?. Collaborative Research Center 386, Discussion Paper 214 [PDF, 221kB]
Klasen, S. and Moradi, A. (2000): The Nutritional Status of Elites in India, Kenya, and Zambia: An appropriate guide for developing reference standards for undernutrition?. Collaborative Research Center 386, Discussion Paper 217 [PDF, 183kB]
Klasen, S. and Woolard, I. (2000): Surviving Unemployment without State Support: Unemployment and Household Formation in South Africa. Collaborative Research Center 386, Discussion Paper 213 [PDF, 216kB]
Klasen, Stephan (2000): Does Gender Inequality Reduce Growth and Development? Evidence from Cross-Country Regressions. Collaborative Research Center 386, Discussion Paper 212 [PDF, 224kB]
Knorr-Held, Leonhard and Best, N. G. (2000): Shared component models for detecting joint and selective clustering of two diseases. Collaborative Research Center 386, Discussion Paper 183 [PDF, 1MB]
Knorr-Held, Leonhard and Rue, H. (2000): On block updating in Markov random field models for disease mapping. (REVISED, May 2001). Collaborative Research Center 386, Discussion Paper 210 [PDF, 841kB]
Kukush, Alexander and Maschke, Erich Otto (2000): The Efficiency of Adjusted Least Squares in the Linear Functional Relationship. Collaborative Research Center 386, Discussion Paper 208 [PDF, 300kB]
Kukush, Alexander and Schneeweiß, Hans (2000): A Comparison of Asymptotic Covariance Matrices of Adjusted Least Squares and Structural Least Squares in Error Ridden Polynomial Regression. Collaborative Research Center 386, Discussion Paper 218 [PDF, 400kB]
Lang, S. and Brezger, Andreas (2000): BayesX - Software for Bayesian Inference based on Markov Chain Monte Carlo simulation techniques. Collaborative Research Center 386, Discussion Paper 187 [PDF, 948kB]
Marx, Brian D. (2000): On Ill-Conditioned Generalized Estimating Equations and Toward Unified Biased Estimation. Collaborative Research Center 386, Discussion Paper 182 [PDF, 390kB]
Pashova, Victoria and Ulm, Kurt (2000): Two Survival Tree Models for Myocardial Infarction Patients. Collaborative Research Center 386, Discussion Paper 195 [PDF, 185kB]
Schneeweiß, Hans and Nittner, T. (2000): Estimating A Polynomial Regression With Measurement Errors In The Structural And In The Functional Case - A Comparison. Collaborative Research Center 386, Discussion Paper 197 [PDF, 290kB]
Seifert-Klauss, V.; Mueller, J. E.; Probst, R.; Wilker, J.; Höß, C.; Treumann, T.; Kastner, C.; Ulm, Kurt and Luppa, P. (2000): Bone Metabolism During the Perimenopausal Transition: a Prospective Study. Collaborative Research Center 386, Discussion Paper 194
Storck, S. (2000): Pattern mixture models for multivariate normal data: a simulation study. Collaborative Research Center 386, Discussion Paper 191 [PDF, 298kB]
Storck, S.; Kastner, C. and Toutenburg, Helge (2000): Longitudinal data with dropouts: a comparison of pattern mixture models with complete case analysis. Collaborative Research Center 386, Discussion Paper 188 [PDF, 264kB]
Toutenburg, Helge and Fieger, A. (2000): Using diagnostic measures to detect non-MCAR processes in linear regression models with missing covariates. Collaborative Research Center 386, Discussion Paper 204 [PDF, 259kB]
Toutenburg, Helge and Srivastava, V. K. (2000): Estimation of Linear Regression Models with Missingness of Observations on Both the Explanatory and Study Variables-Part I: Theoretical Results. Collaborative Research Center 386, Discussion Paper 184 [PDF, 250kB]
Toutenburg, Helge and Srivastava, V. K. (2000): Efficient Estimation of Population Mean Using Incomplete Survey Data on Study and Auxiliary Characteristics. Collaborative Research Center 386, Discussion Paper 179 [PDF, 244kB]
Tutz, Gerhard and Scholz, T. (2000): Semiparametric Modelling of Multicategorical Data. Collaborative Research Center 386, Discussion Paper 209 [PDF, 313kB]
Ulm, Kurt; Schmidt, Georg; Barthel, Petra; Schneider, Raphael; Pashova, Victoria; Rolnitzky, Linda; Bigger Jr., J. Thomas and Schömig, Albert (2000): A Statistical Model for Risk Stratification on the Basis of Left Ventricular Ejection Fraction and Heart-Rate Turbulence. Collaborative Research Center 386, Discussion Paper 198 [PDF, 193kB]
Wolff, J. and Augustin, Thomas (2000): Heaping and its Consequences for Duration Analysis. Collaborative Research Center 386, Discussion Paper 203 [PDF, 480kB]
Ziegler, Andreas and Kastner, C. (2000): The Effect of Misspecified Response Probabilities on Parameter Estimates from Weighted Estimating Equations. Collaborative Research Center 386, Discussion Paper 200 [PDF, 309kB]
Ziegler, Andreas; Kastner, C. and Chang-Claude, J. (2000): Analysis of Pregnancy and Other Factors on Detection of Human Papilloma Virus (HPV) Infection Using Weighted Estimating Equations for Follow-Up Data. Collaborative Research Center 386, Discussion Paper 201 [PDF, 316kB]"

papers_2001 <- "Augustin, Thomas and Coolen, F. P. A. (2001): Nonparametric predictive inference and interval probability. Collaborative Research Center 386, Discussion Paper 257 [PDF, 410kB]
Augustin, Thomas and Pöhlmann, S. (2001): On Robust Sequential Analysis - Kiefer-Weiss Optimal Testing under Interval Probability. Collaborative Research Center 386, Discussion Paper 261 [PDF, 376kB]
Augustin, Thomas and Schwarz, R. (2001): Cox's Proportional Hazards Model under Covariate Measurement Error - A Review and Comparison of Methods. Collaborative Research Center 386, Discussion Paper 260 [PDF, 328kB]
Cheng, Chi-Lun and Schneeweiß, Hans (2001): On the Polynomial Measurement Error Model. Collaborative Research Center 386, Discussion Paper 259 [PDF, 285kB]
Czado, Claudia (2001): Individual Migraine Risk Management using Binary State Space Mixed Models. Collaborative Research Center 386, Discussion Paper 235 [PDF, 459kB]
Czado, Claudia and Raftery, A. E. (2001): Choosing the Link Function and Accounting for Link Uncertainty in Generalized Linear Models using Bayes Factors. Collaborative Research Center 386, Discussion Paper 262 [PDF, 367kB]
Czado, Claudia and Song, Peter X.-K. (2001): State Space Mixed Models for Longitudinal Observations with Binary and Binomial Responses. Collaborative Research Center 386, Discussion Paper 232 [PDF, 491kB]
Einbeck, Jochen (2001): Local Fitting with General Basis Functions. Collaborative Research Center 386, Discussion Paper 256 [PDF, 408kB]
Einbeck, Jochen and Kauermann, Göran (2001): Online Monitoring with Local Smoothing Methods and Adaptive Ridging. Collaborative Research Center 386, Discussion Paper 248 [PDF, 460kB]
Kandala, N. B.; Lang, S.; Klasen, S. and Fahrmeir, Ludwig (2001): Semiparametric Analysis of the Socio-Demographic and Spatial Determinants of Undernutrition in Two African Countries. Collaborative Research Center 386, Discussion Paper 245 [PDF, 322kB]
Kauermann, Göran (2001): Edge Preserving Smoothing by Local Mixture Modelling. Collaborative Research Center 386, Discussion Paper 255 [PDF, 559kB]
Kauermann, Göran and Opsomer, J. D. (2001): A fast method for implementing Generalized Cross-Validation in multi-dimensional nonparametric regression. Collaborative Research Center 386, Discussion Paper 247 [PDF, 394kB]
Kauermann, Göran and Tutz, Gerhard (2001): Vanishing of Risk Factors for the Success and Survival of Newly Founded Companies. Collaborative Research Center 386, Discussion Paper 242 [PDF, 343kB]
Klüppelberg, Claudia; Maller, R. A.; Van De Vyver, M. and Wee, D. (2001): Testing for Reduction to Random Walk in Autoregressive Conditional Heteroskedasticity Models. Collaborative Research Center 386, Discussion Paper 266 [PDF, 376kB]
Klüppelberg, Claudia and Pergamenchtchikov, S. (2001): Renewal Theory for Functionals of a Markov Chain with Compact State Space. Collaborative Research Center 386, Discussion Paper 264 [PDF, 424kB]
Klüppelberg, Claudia and Severin, M. (2001): Prediction of outstanding insurance claims. Collaborative Research Center 386, Discussion Paper 258 [PDF, 504kB]
Knorr-Held, Leonhard; Raßer, Günter and Becker, Nikolaus (2001): Disease Mapping of Stage-specific Cancer Incidence Data. Collaborative Research Center 386, Discussion Paper 249 [PDF, 552kB]
Kukush, Alexander; Schneeweiß, Hans and Wolf, R. (2001): Three Estimators for the Poisson Regression Model with Measurement Errors. Collaborative Research Center 386, Discussion Paper 243 [PDF, 322kB]
Kukush, Alexander; Schneeweiß, Hans and Wolf, R. (2001): Comparison of three estimators in a polynomial regression with measurement errors. Collaborative Research Center 386, Discussion Paper 233 [PDF, 339kB]
Lang, S. and Brezger, Andreas (2001): Bayesian P-Splines. Collaborative Research Center 386, Discussion Paper 236 [PDF, 745kB]
Lang, S. and Fahrmeir, Ludwig (2001): Bayesian generalized additive mixed models. A simulation study. Collaborative Research Center 386, Discussion Paper 230 [PDF, 1MB]
Lang, S.; Fronk, Eva-Maria and Fahrmeir, Ludwig (2001): Function estimation with locally adaptive dynamic models. Collaborative Research Center 386, Discussion Paper 263 [PDF, 540kB]
Lang, S.; Kragler, P.; Haybach, G. and Fahrmeir, Ludwig (2001): Bayesian space-time analysis of health insurance data. Collaborative Research Center 386, Discussion Paper 237 [PDF, 598kB]
Salanti, G. and Ulm, Kurt (2001): Modelling Under Order Restrictions. Collaborative Research Center 386, Discussion Paper 265 [PDF, 319kB]
Salanti, G. and Ulm, Kurt (2001): Multidimensional isotonic regression and estimation of the threshold value. Collaborative Research Center 386, Discussion Paper 234 [PDF, 231kB]
Staubach, C.; Schmid, Volker J.; Ziller, M. and Knorr-Held, Leonhard (2001): A Bayesian Model for Spatial Disease Prevalence Data. Collaborative Research Center 386, Discussion Paper 254 [PDF, 2MB]
Toutenburg, Helge and Shalabh (2001): Synthesizing the classical and inverse methods in linear calibration. Collaborative Research Center 386, Discussion Paper 252 [PDF, 237kB]
Toutenburg, Helge and Shalabh (2001): Use of prior information in the form of interval constraints for the improved estimation of linear regression models with some missing responses. Collaborative Research Center 386, Discussion Paper 240 [PDF, 283kB]
Toutenburg, Helge and Shalabh (2001): Estimation of linear models with missing data: The role of stochastic linear constraints. Collaborative Research Center 386, Discussion Paper 239 [PDF, 242kB]
Toutenburg, Helge and Shalabh (2001): A note on the comparison of minimax linear and mixed regression estimation of regression coefficients when prior estimates are available. Collaborative Research Center 386, Discussion Paper 238 [PDF, 209kB]
Toutenburg, Helge and Srivastava, V. K. (2001): A Revisit to the Application of Weighted Mixed Regression Estimation in Linear Regression Models with Missing Data. Collaborative Research Center 386, Discussion Paper 241 [PDF, 278kB]
Tutz, Gerhard (2001): Generalized semiparametrically structured mixed models. Collaborative Research Center 386, Discussion Paper 251 [PDF, 436kB]
Tutz, Gerhard (2001): Generalized semiparametrically structured ordinal models. Collaborative Research Center 386, Discussion Paper 250 [PDF, 445kB]
Wolff, J. (2001): The Hungarian Unemployment Insurance Benefit System and Incentives to Return to Work. Collaborative Research Center 386, Discussion Paper 253 [PDF, 244kB]"

papers_2002 <- "Adebayo, Samson B. and Fahrmeir, Ludwig (2002): Analyzing Child Mortality in Nigeria with Geoadditive Survival Models. Collaborative Research Center 386, Discussion Paper 303 [PDF, 351kB]
Augustin, Thomas (2002): An exact corrected log-likelihood function for Cox's proportional hazards model under measurement error and some extensions. Collaborative Research Center 386, Discussion Paper 277 [PDF, 242kB]
Augustin, Thomas (2002): Generalized basic probability assignments. Collaborative Research Center 386, Discussion Paper 276 [PDF, 217kB]
Berger, U.; Fahrmeir, Ludwig and Klasen, S. (2002): Dynamic Modelling of Child Mortality in Developing Countries: Application for Zambia. Collaborative Research Center 386, Discussion Paper 299 [PDF, 294kB]
Blauth, A. and Pigeot, Iris (2002): Using Genetic Algorithms for Model Selection in Graphical Models. Collaborative Research Center 386, Discussion Paper 278 [PDF, 375kB]
Böheim, R. (2002): Why are West African children underweight?. Collaborative Research Center 386, Discussion Paper 274 [PDF, 326kB]
Böheim, R. (2002): The association between reported and calculated reservation wages. Collaborative Research Center 386, Discussion Paper 273 [PDF, 393kB]
Czado, Claudia and Gschlößl, Susanne (2002): Modeling of transition intensities and probabilities in a German long term care portfolio with known diagnosis. Collaborative Research Center 386, Discussion Paper 302 [PDF, 445kB]
Czado, Claudia and Rudolph, F. (2002): Application of Survival Analysis Methods to Long Term Care Insurance. Collaborative Research Center 386, Discussion Paper 268 [PDF, 487kB]
Czado, Claudia and Sikora, I. (2002): Quantifying overdispersion effects in count regression data. Collaborative Research Center 386, Discussion Paper 289 [PDF, 472kB]
Di Serio, C. and Vicard, P. (2002): Graphical chain models for the analysis of complex genetic diseases: an application to hypertension. Collaborative Research Center 386, Discussion Paper 288 [PDF, 338kB]
Einbeck, Jochen (2002): Multivariate Local Fitting with General Basis Functions. Collaborative Research Center 386, Discussion Paper 292 [PDF, 562kB]
Einbeck, Jochen; Diva Saldiva de André, C. and Singer, J. (2002): Local Smoothing with Robustness against Outlying Predictors. Collaborative Research Center 386, Discussion Paper 290 [PDF, 357kB]
Fronk, Eva-Maria (2002): Model Selection for Dags via RJMCMC for the Discrete and Mixed Case. Collaborative Research Center 386, Discussion Paper 271 [PDF, 373kB]
Hahn, Klaus; Rodenacker, K. and Auer, Dorothee P. (2002): Intensity Segmentation of the Human Brain with Tissue dependent Homogenization. Collaborative Research Center 386, Discussion Paper 296 [PDF, 2MB]
Kandala, N. B.; Fahrmeir, Ludwig and Klasen, S. (2002): Geo-additive models of Childhood Undernutrition in three Sub-Saharan African Countries. Collaborative Research Center 386, Discussion Paper 287 [PDF, 1MB]
Kauermann, Göran and Berger, U. (2002): A Smooth Test in Proportional Hazard Survival Models using Local Partial Likelihood Fitting. Collaborative Research Center 386, Discussion Paper 282 [PDF, 416kB]
Kauermann, Göran and Küchenhoff, Helmut (2002): Modelling Data from Inside of Earth: Local Smoothing of Mean and Dispersion Structure in Deep Drill Data. Collaborative Research Center 386, Discussion Paper 269 [PDF, 559kB]
Kiselev, V. G.; Hahn, Klaus and Auer, Dorothee P. (2002): Is the Brain Cortex a Fractal?. Collaborative Research Center 386, Discussion Paper 297 [PDF, 392kB]
Klüppelberg, Claudia (2002): Risk Management with Extreme Value Theory. Collaborative Research Center 386, Discussion Paper 270 [PDF, 1MB]
Klüppelberg, Claudia and Pergamenchtchikov, S. (2002): The Tail of the Stationary Distribution of a Random Coefficient AR(q) Model. Collaborative Research Center 386, Discussion Paper 267 [PDF, 439kB]
Kukush, Alexander; Schneeweiß, Hans and Wolf, R. (2002): Comparing Different Estimators in a Nonlinear Measurement Error Model. Collaborative Research Center 386, Discussion Paper 244 [PDF, 522kB]
Kukush, Alexander and Shklyar, Sergiy (2002): Comparison of three estimators in Poisson errors-in-variables model with one covariate. Collaborative Research Center 386, Discussion Paper 293 [PDF, 350kB]
Lang, Stefan; Adebayo, Samson B.; Fahrmeir, Ludwig and Steiner, Winfried J. (2002): Bayesian Geoadditive Seemingly Unrelated Regression. Collaborative Research Center 386, Discussion Paper 300 [PDF, 683kB]
Müller, Gernot and Czado, Claudia (2002): Regression Models for Ordinal Valued Time Series with Application to High Frequency Financial Data. Collaborative Research Center 386, Discussion Paper 301 [PDF, 427kB]
Nittner, T. (2002): Missing at Random (MAR) in Nonparametric Regression - A Simulation Experiment. Collaborative Research Center 386, Discussion Paper 284 [PDF, 411kB]
Nittner, T. (2002): The Additive Model with Missing Values in the Independent Variable - Theory and Simulation. Collaborative Research Center 386, Discussion Paper 272 [PDF, 456kB]
Odejar, M. A. E. (2002): Bayesian Analysis of Sample Selection and Endogenous Switching Regression Models with Random Coefficients Via MCMC Methods. Collaborative Research Center 386, Discussion Paper 291 [PDF, 1MB]
Payer, T. and Küchenhoff, Helmut (2002): Modelling extreme wind speeds in the context of risk analysis for high speed trains. Collaborative Research Center 386, Discussion Paper 295 [PDF, 250kB]
Scheid, S. (2002): A Selection Model for Bivariate Normal Data, with a Flexible Nonparametric Missing Model and a Focus on Variance Estimates. Collaborative Research Center 386, Discussion Paper 285 [PDF, 277kB]
Schneeweiß, Hans; Cheng, Chi-Lun and Wolf, R. (2002): On the bias of structural estimation methods in a polynomial regression with measurement error when the distribution of the latent covariate is a mixture of normals. Collaborative Research Center 386, Discussion Paper 281 [PDF, 373kB]
Shklyar, Sergiy and Schneeweiß, Hans (2002): A comparison of asymptotic covariance matrices of three consistent estimators in the Poisson regression model with measurement errors. Collaborative Research Center 386, Discussion Paper 283 [PDF, 333kB]
Toutenburg, Helge; Heumann, Christian; Nittner, T. and Scheid, S. (2002): Parametric and Nonparametric Regression with Missing X's - A Review. Collaborative Research Center 386, Discussion Paper 286 [PDF, 388kB]
Tutz, Gerhard (2002): Modelling of repeated ordered measurements by isotonic sequential regression. Collaborative Research Center 386, Discussion Paper 298 [PDF, 244kB]
Tutz, Gerhard and Binder, Harald (2002): Flexible Modelling of Discrete Failure Time Including Time-Varying Smooth Effects. Collaborative Research Center 386, Discussion Paper 294 [PDF, 361kB]"

papers_2003 <- "Augustin, Thomas; Döring, A. and Rummel, D. (2003): Regression calibration for Cox regression under heteroscedastic measurement error - Determining risk factors of cardiovascular diseases from error-prone nutritional replication data. Collaborative Research Center 386, Discussion Paper 345 [PDF, 331kB]
Bender, R.; Augustin, Thomas and Blettner, Maria (2003): Generating Survival Times to Simulate Cox Proportional Hazards Models. Collaborative Research Center 386, Discussion Paper 338 [PDF, 159kB]
Bender, S.; Kohlmann, A. and Lang, S. (2003): Women, Work, and Motherhood: Changing Employment Penalties for Motherhood in West Germany after 1945 -- A Comparative Analysis of Cohorts Born in 1934-1971. Collaborative Research Center 386, Discussion Paper 309 [PDF, 385kB]
Boulesteix, Anne-Laure; Hösel, V. and Liebscher, V. (2003): Stochastic modeling for the COMET-assay. Collaborative Research Center 386, Discussion Paper 336 [PDF, 229kB]
Boulesteix, Anne-Laure and Tutz, Gerhard (2003): A Framework to Discover Emerging Patterns for Application in Microarray Data. Collaborative Research Center 386, Discussion Paper 313 [PDF, 232kB]
Brezger, Andreas; Kneib, Thomas and Lang, S. (2003): BayesX: Analysing Bayesian structured additive regression models. Collaborative Research Center 386, Discussion Paper 332 [PDF, 312kB]
Brezger, Andreas and Lang, S. (2003): Generalized structured additive regression based on Bayesian P-splines. Collaborative Research Center 386, Discussion Paper 321 [PDF, 748kB]
Brezger, Andreas and Steiner, Winfried J. (2003): Monotonic regression based on Bayesian P-splines: an application to estimating price response functions from store-level scanner data. Collaborative Research Center 386, Discussion Paper 331 [PDF, 489kB]
Czado, Claudia and Gschlößl, Susanne (2003): The inception selection effect of diagnosis in a German long term care portfolio. Collaborative Research Center 386, Discussion Paper 357 [PDF, 413kB]
Di Serio, C. and Lamina, C. (2003): Bayesian P-Splines to investigate the impact of covariates on Multiple Sclerosis clinical course. Collaborative Research Center 386, Discussion Paper 353 [PDF, 1MB]
Einbeck, Jochen; Tutz, Gerhard and Evers, L. (2003): Local Principal Curves. Collaborative Research Center 386, Discussion Paper 320 [PDF, 445kB]
Fahrmeir, Ludwig; Gössl, Christoff and Hennerfeind, Andrea (2003): Bayesian mapping of brain regions using compound Markov random field priors. Collaborative Research Center 386, Discussion Paper 317 [PDF, 1MB]
Fahrmeir, Ludwig and Hennerfeind, Andrea (2003): Nonparametric Bayesian hazard rate models based on penalized splines. Collaborative Research Center 386, Discussion Paper 361 [PDF, 406kB]
Fahrmeir, Ludwig; Kneib, Thomas and Lang, S. (2003): Penalized additive regression for space-time data: a Bayesian perspective. Collaborative Research Center 386, Discussion Paper 305 [PDF, 753kB]
Fahrmeir, Ludwig and Osuna, L. (2003): Structured count data regression. Collaborative Research Center 386, Discussion Paper 334 [PDF, 1MB]
Friedrich, F.; Winkler, Gerhard; Wittich, O. and Liebscher, V. (2003): An Elementary Rigorous Introduction to Exact Sampling. Collaborative Research Center 386, Discussion Paper 329 [PDF, 382kB]
Gartner, H. and Scheid, S. (2003): Multiple Imputation von fehlenden Werten mit Daten über Unterernährung und Kindersterblichkeit. Collaborative Research Center 386, Discussion Paper 322 [PDF, 392kB]
Gartner, H. and Scholz, T. (2003): Das Auszugsverhalten junger Menschen. Collaborative Research Center 386, Discussion Paper 315 [PDF, 414kB]
Gehrmann, U.; Hellriegel, B.; Neiss, A. and Fahrmeir, Ludwig (2003): Analysis of the time to sustained progression in Multiple Sclerosis using generalised linear and additive models. Collaborative Research Center 386, Discussion Paper 354 [PDF, 375kB]
Hahn, Klaus; Prigarin, Sergej and Pütz, Benno (2003): Spatial Smoothing for Diffusion Tensor Imaging with low Signal to Noise Ratios. Collaborative Research Center 386, Discussion Paper 358 [PDF, 1MB]
Heim, Susanne; Hahn, Klaus and Auer, Dorothee P. (2003): Diffusion Tensor Imaging: on the assessment of data quality - a preliminary bootstrap analysis. Collaborative Research Center 386, Discussion Paper 356 [PDF, 952kB]
Hellriegel, B.; Daumer, Martin and Neiß, A. (2003): Analysing the course of multiple sclerosis with segmented regression models. Collaborative Research Center 386, Discussion Paper 355 [PDF, 248kB]
Hennerfeind, Andrea; Brezger, Andreas and Fahrmeir, Ludwig (2003): Geoadditive survival models. Collaborative Research Center 386, Discussion Paper 333 [PDF, 4MB]
Holmes, C. and Knorr-Held, Leonhard (2003): Efficient simulation of Bayesian logistic regression models. Collaborative Research Center 386, Discussion Paper 306 [PDF, 315kB]
Högn, Ralph and Czado, Claudia (2003): Theoretical Foundations of Autoregressive Models for Time Series on Acyclic Directed Graphs. Collaborative Research Center 386, Discussion Paper 326 [PDF, 2MB]
Jerak, A. and Lang, S. (2003): Locally Adaptive Function Estimation for Binary Regression Models. Collaborative Research Center 386, Discussion Paper 310 [PDF, 330kB]
Jerak, A. and Wagner, S. (2003): Modeling Probabilities of Patent Oppositions in a Bayesian Semiparametric Regression Framework. Collaborative Research Center 386, Discussion Paper 323 [PDF, 309kB]
Kehl, V. and Ulm, Kurt (2003): Responder Identification in Clinical Trials with Censored Data. Collaborative Research Center 386, Discussion Paper 311 [PDF, 452kB]
Kehl, V.; Ulm, Kurt; Schmidt, G.; Barthel, Petra and Malik, M. (2003): Identification of Responders to Amiodarone: Subgroup Analysis of the EMIAT Study. Collaborative Research Center 386, Discussion Paper 366 [PDF, 316kB]
Klasen, S. and Launov, A. (2003): Analysis of the Determinants of Fertility Decline in the Czech Republic. Collaborative Research Center 386, Discussion Paper 352 [PDF, 707kB]
Klüppelberg, Claudia; Lindner, Alexander M. and Maller, R. A. (2003): Stationarity and second order behaviour of discrete and continuous time GARCH(1,1) processes. Collaborative Research Center 386, Discussion Paper 337 [PDF, 673kB]
Knüsel, L. (2003): Alternatives to the MCMC method. Collaborative Research Center 386, Discussion Paper 367 [PDF, 504kB]
Krause, Rüdiger and Tutz, Gerhard (2003): Additive Modelling with Penalized Regression Splines and Genetic Algorithms. Collaborative Research Center 386, Discussion Paper 312 [PDF, 652kB]
Küchenhoff, Helmut; Bender, R.; Langner, I. and Lenz-Tönjes, R. (2003): Effect of Berkson measurement error on parameter estimates in Cox regression models. Collaborative Research Center 386, Discussion Paper 346 [PDF, 297kB]
Langner, I.; Bender, R.; Lenz-Tönjes, R.; Küchenhoff, Helmut and Blettner, Maria (2003): Bias of Maximum-Likelihood estimates in logistic and Cox regression models: A comparative simulation study. Collaborative Research Center 386, Discussion Paper 362 [PDF, 376kB]
Launov, A. (2003): A Study of the Austrian Labour Makret Dynamics Using a Model of Search Equilibrium. Collaborative Research Center 386, Discussion Paper 351 [PDF, 427kB]
Lindner, A. and Meyer, K. (2003): Extremal behavior of finite EGARCH Processes. Collaborative Research Center 386, Discussion Paper 347 [PDF, 393kB]
Martin, A. (2003): Small Ball Asymptotics for the Stochastic Wave Equation. Collaborative Research Center 386, Discussion Paper 360 [PDF, 389kB]
Martin, A.; Prigarin, Sergej and Winkler, Gerhard (2003): Exact and Fast Numerical Algorithms for the Stochastic Wave Equation. Collaborative Research Center 386, Discussion Paper 349 [PDF, 325kB]
Martin, A.; Prigarin, Sergej and Winkler, Gerhard (2003): Exact numerical algorithms for linear stochastic wave equation and stochastic Klein-Gordon equation. Collaborative Research Center 386, Discussion Paper 327 [PDF, 240kB]
Müller, Gernot; Czado, Claudia; Antes, Stefan and Rottenwallner, Martin (2003): Regression Models for Ordinal Valued Time Series: Applications in High Frequency Finance and Medicine. Collaborative Research Center 386, Discussion Paper 335 [PDF, 1MB]
Müller, M. and Ulm, Kurt (2003): Implementation of complex interactions in a Cox regression framework. Collaborative Research Center 386, Discussion Paper 363 [PDF, 489kB]
Prigarin, Sergej and Winkler, Gerhard (2003): Numerical solution of boundary value problems for stochastic differential equations on the basis of the Gibbs sampler. Collaborative Research Center 386, Discussion Paper 328 [PDF, 229kB]
Salanti, G. and Ulm, Kurt (2003): Modelling time-varying effects in Cox model under order restrictions. Collaborative Research Center 386, Discussion Paper 319 [PDF, 322kB]
Schmid, Volker J. and Held, Leonhard (2003): Bayesian modelling of space-time interactions on the Lexis diagram. Collaborative Research Center 386, Discussion Paper 314 [PDF, 378kB]
Schneeweiß, Hans (2003): Estimating the endpoint of a uniform distribution under normal measurement errors with known error variance. Collaborative Research Center 386, Discussion Paper 339 [PDF, 215kB]
Schneeweiß, Hans and Cheng, Chi-Lun (2003): Bias of the Quasi Score Estimator of a Measurement Error Model Under Misspecification of the Regressor Distribution. Collaborative Research Center 386, Discussion Paper 340 [PDF, 366kB]
Schneeweiß, Hans; Maschke, Erich Otto and Pfannes, Manfred (2003): The Reduced Form of a Block Recursive Model. Collaborative Research Center 386, Discussion Paper 307 [PDF, 319kB]
Smith, Michael; Pütz, Benno; Auer, Dorothee P. and Fahrmeir, Ludwig (2003): Assessing Brain Activity through Spatial Bayesian Variable Selection. Collaborative Research Center 386, Discussion Paper 316 [PDF, 399kB]
Strobl, R.; Salanti, G. and Ulm, Kurt (2003): Extension of CART using multiple splits under order restrictions. Collaborative Research Center 386, Discussion Paper 364 [PDF, 552kB]
Tutz, Gerhard (2003): Response smoothing estimators in binary regression. Collaborative Research Center 386, Discussion Paper 318 [PDF, 460kB]
Tutz, Gerhard and Hechenbichler, K. (2003): Aggregating Classifiers With Ordinal Response Structure. Collaborative Research Center 386, Discussion Paper 359 [PDF, 369kB]
Tutz, Gerhard and Scholz, T. (2003): Ordinal regression modelling between proportional odds and non-proportional odds. Collaborative Research Center 386, Discussion Paper 304 [PDF, 407kB]
Ulm, Kurt; Barthel, Petra; Rolnitzky, Linda; Schneider, Raphael; Malik, M.; Bigger Jr., J. Thomas and Schmidt, Georg (2003): Risk Stratification in Post-MI Patients Based on Left Ventricular Ejection Fraction and Heart-Rate Turbulence. Collaborative Research Center 386, Discussion Paper 365 [PDF, 213kB]
Winkler, Gerhard; Kempe, A.; Liebscher, V. and Wittich, O. (2003): Parsimonious Segmentation of Time Series' by Potts Models. Collaborative Research Center 386, Discussion Paper 348 [PDF, 295kB]
Wolff, J. (2003): Unemployment Benefits and the Duration of Unemployment in East Germany. Collaborative Research Center 386, Discussion Paper 344 [PDF, 374kB]
Wolff, J. and Trübswetter, P. (2003): The Speed of Leaving the Old Job: A Study on Job Changes and Exit into Unemployment during the East German Transition Process. Collaborative Research Center 386, Discussion Paper 343 [PDF, 389kB]"

papers_2004 <- "Adejumo, A. O.; Heumann, Christian and Toutenburg, Helge (2004): Modelling Negative Binomial as a substitute model to Poisson for raters agreement on ordinal scales with sparse data. Collaborative Research Center 386, Discussion Paper 387 [PDF, 263kB]
Adejumo, A. O.; Heumann, Christian and Toutenburg, Helge (2004): Conditional symmetry model as a better alternative to Symmetry Model for rater agreement measure. Collaborative Research Center 386, Discussion Paper 386 [PDF, 230kB]
Adejumo, A. O.; Heumann, Christian and Toutenburg, Helge (2004): A review of agreement measure as a subset of association measure between raters. Collaborative Research Center 386, Discussion Paper 385 [PDF, 356kB]
Barndorff-Nielsen, Ole Eiler and Lindner, Alexander M. (2004): Some aspects of Lévy copulas. Collaborative Research Center 386, Discussion Paper 388 [PDF, 454kB]
Barndorff-Nielsen, Ole Eiler and Stelzer, Robert (2004): Absolute Moments of Generalized Hyperbolic Distributions and Approximate Scaling of Normal Inverse Gaussian Lévy-Processes. Collaborative Research Center 386, Discussion Paper 381 [PDF, 328kB]
Boulesteix, Anne-Laure (2004): A note on between-group PCA. Collaborative Research Center 386, Discussion Paper 397 [PDF, 174kB]
Boulesteix, Anne-Laure (2004): PLS dimension reduction for classification of microarray data. Collaborative Research Center 386, Discussion Paper 392 [PDF, 276kB]
Boulesteix, Anne-Laure and Tutz, Gerhard (2004): Identification of Interaction Patterns and Classification with Applications to Microarray Data. Collaborative Research Center 386, Discussion Paper 369 [PDF, 317kB]
Czado, Claudia; Delwarde, A. and Denuit, M. (2004): Bayesian Poisson Log-Bilinear Mortality Projections. Collaborative Research Center 386, Discussion Paper 398 [PDF, 1MB]
Czado, Claudia and Kolbe, A. (2004): Empirical Study of Intraday Option Price Changes using extended Count Regression Models. Collaborative Research Center 386, Discussion Paper 403 [PDF, 363kB]
Czado, Claudia and Kolbe, A. (2004): Statistical Analysis of Absolute Transaction Price Changes of Options. Collaborative Research Center 386, Discussion Paper 384 [PDF, 662kB]
Czado, Claudia and Prokopenko, S. (2004): Modeling Transport Mode Decisions Using Hierarchical Binary Spatial Regression Models with Cluster Effects. Collaborative Research Center 386, Discussion Paper 406 [PDF, 2MB]
Einbeck, Jochen and Tutz, Gerhard (2004): Modelling beyond Regression Functions: an Application of Multimodal Regression to Speed-Flow Data. Collaborative Research Center 386, Discussion Paper 395 [PDF, 437kB]
Hechenbichler, K. and Schliep, K. (2004): Weighted k-Nearest-Neighbor Techniques and Ordinal Classification. Collaborative Research Center 386, Discussion Paper 399 [PDF, 229kB]
Held, Leonhard; Höhle, Michael and Hofmann, M. (2004): A statistical framework for the analysis of multivariate infectious disease surveillance data. Collaborative Research Center 386, Discussion Paper 402 [PDF, 563kB]
Held, Leonhard and Ranyimbo, Argwings Otiemo (2004): Bayesian estimation of the false negative fraction in screening tests. Collaborative Research Center 386, Discussion Paper 376 [PDF, 250kB]
Helms, F.; Czado, Claudia and Gschlößl, Susanne (2004): Calculation of LTC Premiums based on direct estimates of transition probabilities. Collaborative Research Center 386, Discussion Paper 393 [PDF, 333kB]
Hofmann, M.; Höhle, Michael and Held, Leonhard (2004): A stochastic model for multivariate surveillance of infectious diseases. Collaborative Research Center 386, Discussion Paper 394 [PDF, 296kB]
Hsing, T.; Klüppelberg, Claudia and Kuhn, Gabriel (2004): Modelling, Estimation and Visualization of Multivariate Dependence for Risk Management. Collaborative Research Center 386, Discussion Paper 375 [PDF, 555kB]
Hsing, T.; Klüppelberg, Claudia and Kuhn, Gabriel (2004): Dependence Estimation and Visualization in Multivariate Extremes with Applications to Financial Data. Collaborative Research Center 386, Discussion Paper 374 [PDF, 736kB]
Kneib, Thomas and Fahrmeir, Ludwig (2004): A mixed model approach for structured hazard regression. Collaborative Research Center 386, Discussion Paper 400 [PDF, 1MB]
Kneib, Thomas and Fahrmeir, Ludwig (2004): Structured additive regression for multicategorical space-time data: A mixed model approach. Collaborative Research Center 386, Discussion Paper 377 [PDF, 520kB]
Krause, Rüdiger and Tutz, Gerhard (2004): Variable selection and discrimination in gene expression data by genetic algorithms. Collaborative Research Center 386, Discussion Paper 390 [PDF, 401kB]
Krause, Rüdiger and Tutz, Gerhard (2004): Simultaneous selection of variables and smoothing parameters by genetic algorithms. Collaborative Research Center 386, Discussion Paper 389 [PDF, 896kB]
Kukush, Alexander and Schneeweiß, Hans (2004): Relative Efficiency of Maximum Likelihood and Other Estimators in a Nonlinear Regression Model with Small Measurement Errors. Collaborative Research Center 386, Discussion Paper 396 [PDF, 211kB]
Linde, A. van der and Tutz, Gerhard (2004): On association in regression: the coefficient of determination revisited. Collaborative Research Center 386, Discussion Paper 391 [PDF, 390kB]
Müller, M. (2004): Goodness-of-fit criteria for survival data. Collaborative Research Center 386, Discussion Paper 382 [PDF, 3MB]
Nittner, T. and Toutenburg, Helge (2004): Identifying Missing Data Mechanisms in (2 x 2)-Contingency Tables. Collaborative Research Center 386, Discussion Paper 373 [PDF, 325kB]
Toutenburg, Helge; Heumann, Christian and Nittner, T. (2004): Statistische Methoden bei unvollständigen Daten. Collaborative Research Center 386, Discussion Paper 380 [PDF, 567kB]
Tutz, Gerhard and Binder, Harald (2004): Generalized additive modelling with implicit variable selection by likelihood based boosting. Collaborative Research Center 386, Discussion Paper 401 [PDF, 370kB]
Tutz, Gerhard and Binder, Harald (2004): Localized Regression. Collaborative Research Center 386, Discussion Paper 378 [PDF, 312kB]
Zempléni, A. (2004): Goodness-of-fit test in extreme value applications. Collaborative Research Center 386, Discussion Paper 383 [PDF, 276kB]"

papers_2005 <- "Boulesteix, Anne-Laure (2005): Maximally selected chi-square statistics and binary splits of nominal variables. Collaborative Research Center 386, Discussion Paper 449 [PDF, 261kB]
Boulesteix, Anne-Laure (2005): Maximally selected chi-square statistics for at least ordinal scaled variables. Collaborative Research Center 386, Discussion Paper 407 [PDF, 238kB]
Boulesteix, Anne-Laure and Strimmer, Korbinian (2005): Partial Least Squares: A Versatile Tool for the Analysis of High-Dimensional Genomic Data. Collaborative Research Center 386, Discussion Paper 457 [PDF, 197kB]
Boulesteix, Anne-Laure and Strimmer, Korbinian (2005): Predicting Transcription Factor Activities from Combined Analysis of Microarray and ChIP Data: A Partial Least Squares Approach. Collaborative Research Center 386, Discussion Paper 411 [PDF, 260kB]
Brezger, Andreas; Fahrmeir, Ludwig and Hennerfeind, Andrea (2005): Adaptive Gaussian Markov Random Fields with Applications in Human Brain Mapping. Collaborative Research Center 386, Discussion Paper 456 [PDF, 601kB]
Brezger, Andreas and Lang, S. (2005): Simultaneous probability statements for Bayesian P-splines. Collaborative Research Center 386, Discussion Paper 437 [PDF, 896kB]
Brockwell, Peter J.; Chadraa, Erdenebaatar and Lindner, Alexander M. (2005): A Continuous Time GARCH Process of Higher Order. Collaborative Research Center 386, Discussion Paper 428 [PDF, 557kB]
Czado, Claudia; Heyn, Anette and Müller, Gernot (2005): Modeling migraine severity with autoregressive ordered probit models. Collaborative Research Center 386, Discussion Paper 463 [PDF, 263kB]
Czado, Claudia; Heyn, Anette and Müller, Gernot (2005): Modeling migraine severity with autoregressive ordered probit models. Collaborative Research Center 386, Discussion Paper 413 [PDF, 302kB]
Czado, Claudia and Min, Aleksey (2005): Consistency and asymptotic normality of the maximum likelihood estimator in a zero-inflated generalized Poisson regression. Collaborative Research Center 386, Discussion Paper 423 [PDF, 398kB]
Dargatz, Christiane; Georgescu, Vera and Held, Leonhard (2005): Stochastic modelling of the spatial spread of influenza in Germany. Collaborative Research Center 386, Discussion Paper 450 [PDF, 781kB]
Ebers, G. C.; Heigenhauser, L.; Daumer, Martin; Lederer, C. and Noseworthy, J. H. (2005): Multiple sclerosis, the measurement of disability and access to clinical trial data. Collaborative Research Center 386, Discussion Paper 429 [PDF, 295kB]
Eilers, Paul H. C.; Heim, Susanne and Marx, Brian D. (2005): Varying Coefficient Tensor Models for Brain Imaging. Collaborative Research Center 386, Discussion Paper 436 [PDF, 228kB]
Einbeck, Jochen and Augustin, Thomas (2005): On weighted local fitting and its relation to the Horvitz-Thompson estimator. Collaborative Research Center 386, Discussion Paper 465 [PDF, 377kB]
Fasen, V.; Klüppelberg, Claudia and Lindner, A. (2005): Extremal behavior of stochastic volatility models. Collaborative Research Center 386, Discussion Paper 427 [PDF, 774kB]
Gschlößl, Susanne and Czado, Claudia (2005): Spatial modelling of claim frequency and claim size in insurance. Collaborative Research Center 386, Discussion Paper 461 [PDF, 2MB]
Gschlößl, Susanne and Czado, Claudia (2005): Does a Gibbs sampler approach to spatial Poisson regression models outperform a single site MH sampler?. Collaborative Research Center 386, Discussion Paper 460 [PDF, 484kB]
Gschlößl, Susanne and Czado, Claudia (2005): Introducing and evaluating a Gibbs sampler for spatial Poisson regression models. Collaborative Research Center 386, Discussion Paper 434 [PDF, 656kB]
Gschlößl, Susanne and Czado, Claudia (2005): Modelling count data with overdispersion and spatial effects. Collaborative Research Center 386, Discussion Paper 412 [PDF, 387kB]
Hahn, Klaus; Prigarin, Sergej; Heim, Susanne and Hasan, Khader (2005): Random noise in Diffusion Tensor Imaging, its Destructive Impact and Some Corrections. Collaborative Research Center 386, Discussion Paper 459 [PDF, 294kB]
Hahn, Klaus; Prigarin, Sergej; Pütz, Benno and Hasan, Khader (2005): DTI denoising for data with low signal to noise ratios. Collaborative Research Center 386, Discussion Paper 409 [PDF, 10MB]
Haug, Stephan and Czado, Claudia (2005): Mixed effect model for absolute log returns of ultra high frequency data. Collaborative Research Center 386, Discussion Paper 440 [PDF, 958kB]
Haug, Stephan; Klüppelberg, Claudia; Lindner, A. and Zapp, M. (2005): Estimating the COGARCH(1,1) model - a first go. Collaborative Research Center 386, Discussion Paper 458 [PDF, 411kB]
Heigenhauser, L.; Confavreux, C.; Daumer, Martin; Ebers, G. C.; Kappos, L.; Lederer, C.; Neiß, A.; Polman, C. and Vukusic, S. (2005): Treating Systematic Errors in Multiple Sclerosis Data. Collaborative Research Center 386, Discussion Paper 435 [PDF, 224kB]
Heim, Susanne; Fahrmeir, Ludwig; Eilers, Paul H. C. and Marx, Brian D. (2005): Space-Varying Coefficient Models for Brain Imaging. Collaborative Research Center 386, Discussion Paper 455 [PDF, 1MB]
Held, Leonhard; Hofmann, M.; Höhle, Michael and Schmid, Volker J. (2005): A two-component model for counts of infectious diseases. Collaborative Research Center 386, Discussion Paper 424 [PDF, 826kB]
Held, U.; Heigenhauser, L.; Shang, C.; Kappos, L. and Polman, C. (2005): Predicting the On-Study Relapse Rate for Multiple Sclerosis Patients in Clinical Trials. Collaborative Research Center 386, Discussion Paper 430 [PDF, 246kB]
Hennerfeind, Andrea; Brezger, Andreas and Fahrmeir, Ludwig (2005): Geoadditive Survival Models: A Supplement. Collaborative Research Center 386, Discussion Paper 454 [PDF, 1MB]
Hennerfeind, Andrea; Brezger, Andreas and Fahrmeir, Ludwig (2005): Geoadditive survival models. Collaborative Research Center 386, Discussion Paper 414 [PDF, 3MB]
Höhle, Michael and Riebler, A. (2005): The R-Package 'surveillance'. Collaborative Research Center 386, Discussion Paper 422 [PDF, 625kB]
Klüppelberg, Claudia and Lindner, A. (2005): Extreme value theory for moving average processes with light-tailed innovations. Collaborative Research Center 386, Discussion Paper 432 [PDF, 400kB]
Klüppelberg, Claudia; Lindner, Alexander M. and Maller, R. A. (2005): Continuous time volatility modelling: COGARCH versus Ornstein-Uhlenbeck models. Collaborative Research Center 386, Discussion Paper 426 [PDF, 387kB]
Klüppelberg, Claudia; Lindner, Alexander M. and Maller, R. A. (2005): A Continuous Time GARCH Process Driven by a Lévy Process: Stationarity and Second Order Behaviour. Collaborative Research Center 386, Discussion Paper 425 [PDF, 550kB]
Kneib, Thomas (2005): Geoadditive hazard regression for interval censored survival times. Collaborative Research Center 386, Discussion Paper 447 [PDF, 616kB]
Kneib, Thomas and Fahrmeir, Ludwig (2005): Supplement to \"Structured additive regression for categorical space-time data: A mixed model approach\". Collaborative Research Center 386, Discussion Paper 431 [PDF, 1MB]
Kuhn, Gabriel (2005): Tails of Credit Default Portfolios. Collaborative Research Center 386, Discussion Paper 410 [PDF, 444kB]
Kukush, Alexander; Schneeweiß, Hans and Shklyar, Sergiy (2005): Quasi Score is more efficient than Corrected Score in a general nonlinear measurement error model. Collaborative Research Center 386, Discussion Paper 451 [PDF, 278kB]
Leitenstorfer, Florian and Tutz, Gerhard (2005): Generalized Monotonic Regression Based on B-Splines with an Application to Air Pollution Data. Collaborative Research Center 386, Discussion Paper 444 [PDF, 681kB]
Lindner, Alexander M. and Szimayer, Alexander (2005): A Limit Theorem for Copulas. Collaborative Research Center 386, Discussion Paper 433 [PDF, 251kB]
Nilsson, D. and Höhle, Michael (2005): Methods for evaluating Decision Problems with Limited Information. Collaborative Research Center 386, Discussion Paper 421 [PDF, 379kB]
Prigarin, Sergej and Hahn, Klaus (2005): Stochastic Algorithms for White Matter Fiber Tracking and the Inference of Brain Connectivity from MR Diffusion Tensor Data. Collaborative Research Center 386, Discussion Paper 408 [PDF, 1MB]
Schmid, Matthias (2005): Estimation of a Linear Model under Microaggregation by Individual Ranking. Collaborative Research Center 386, Discussion Paper 453 [PDF, 286kB]
Schmid, Matthias and Schneeweiß, Hans (2005): Estimation of a Linear Regression under Microaggregation with the Response Variable as a Sorting Variable. Collaborative Research Center 386, Discussion Paper 462 [PDF, 282kB]
Schmid, Matthias and Schneeweiß, Hans (2005): The Effect of Microaggregation Procedures on the Estimation of Linear Models: A Simulation Study. Collaborative Research Center 386, Discussion Paper 443 [PDF, 369kB]
Schmid, Matthias; Schneeweiß, Hans and Küchenhoff, Helmut (2005): Statistical Inference in a Simple Linear Model Under Microaggregation. Collaborative Research Center 386, Discussion Paper 416 [PDF, 352kB]
Schmid, Matthias; Schneeweiß, Hans and Küchenhoff, Helmut (2005): Consistent Estimation of a Simple Linear Model Under Microaggregation. Collaborative Research Center 386, Discussion Paper 415 [PDF, 421kB]
Schneeweiß, Hans (2005): The polynomial and the Poisson measurement error models: some further results on quasi score and corrected score estimation. Collaborative Research Center 386, Discussion Paper 446 [PDF, 427kB]
Schneeweiß, Hans (2005): Abraham Wald. Collaborative Research Center 386, Discussion Paper 439 [PDF, 242kB]
Schneeweiß, Hans and Augustin, Thomas (2005): Some Recent Advances in Measurement Error Models and Methods. Collaborative Research Center 386, Discussion Paper 452 [PDF, 289kB]
Shalabh and Toutenburg, Helge (2005): On the regression method of estimation of population mean from incomplete survey data through imputation. Collaborative Research Center 386, Discussion Paper 442 [PDF, 290kB]
Shalabh and Toutenburg, Helge (2005): Consequences of Departure from Normality on the Properties of Calibration Estimators. Collaborative Research Center 386, Discussion Paper 441 [PDF, 248kB]
Shklyar, Sergiy; Schneeweiß, Hans and Kukush, Alexander (2005): Quasi Score is more efficient than Corrected Score in a polynomial measurement error model. Collaborative Research Center 386, Discussion Paper 445 [PDF, 261kB]
Steiner, Winfried J.; Belitz, Christiane and Lang, Stefan (2005): Semiparametric Stepwise Regression to Estimate Sales Promotion Effects. Collaborative Research Center 386, Discussion Paper 438 [PDF, 191kB]
Strobl, Carolin (2005): Statistical Sources of Variable Selection Bias in Classification Tree Algorithms Based on the Gini Index. Collaborative Research Center 386, Discussion Paper 420 [PDF, 196kB]
Strobl, Carolin (2005): Variable Selection Bias in Classification Trees Based on Imprecise Probabilities. Collaborative Research Center 386, Discussion Paper 419 [PDF, 325kB]
Strobl, Carolin; Boulesteix, Anne-Laure and Augustin, Thomas (2005): Unbiased split selection for classification trees based on the Gini Index. Collaborative Research Center 386, Discussion Paper 464 [PDF, 237kB]
Tutz, Gerhard and Binder, Harald (2005): Boosting Ridge Regression. Collaborative Research Center 386, Discussion Paper 418 [PDF, 1MB]
Tutz, Gerhard and Leitenstorfer, Florian (2005): Generalized smooth monotonic regression. Collaborative Research Center 386, Discussion Paper 417 [PDF, 1MB]
Tutz, Gerhard and Reithinger, Florian (2005): Flexible semiparametric mixed models. Collaborative Research Center 386, Discussion Paper 448 [PDF, 1MB]"

papers_2006 <- "Aas, Kjersti; Czado, Claudia; Frigessi, Arnoldo and Bakken, Henrik (2006): Pair-copula constructions of multiple dependence. Collaborative Research Center 386, Discussion Paper 487 [PDF, 1MB]
Boulesteix, Anne-Laure and Strobl, Carolin (2006): Maximally selected chi-square statistics and umbrella orderings. Collaborative Research Center 386, Discussion Paper 476 [PDF, 272kB]
Coolen, F. P. A. and Augustin, Thomas (2006): A nonparametric predictive alternative to the Imprecise Dirichlet Model: the case of a known number of categories. Collaborative Research Center 386, Discussion Paper 489 [PDF, 303kB]
Czado, Claudia; Erhardt, Vinzenz and Min, Aleksey (2006): Zero-inflated generalized Poisson models with regression effects on the mean, dispersion and zero-inflation level applied to patent outsourcing rates. Collaborative Research Center 386, Discussion Paper 482 [PDF, 497kB]
Czado, Claudia and Haug, Stephan (2006): Quasi maximum likelihood estimation and prediction in the compound Poisson ECOGARCH(1,1) model. Collaborative Research Center 386, Discussion Paper 516 [PDF, 926kB]
Czado, Claudia and Haug, Stephan (2006): A fractionally integrated ECOGARCH process. Collaborative Research Center 386, Discussion Paper 484 [PDF, 439kB]
Czado, Claudia and Min, Aleksey (2006): Testing for zero-modification in count regression models. Collaborative Research Center 386, Discussion Paper 474 [PDF, 299kB]
Czado, Claudia and Pflüger, Carolin (2006): Modeling dependencies between rating categories and their effects on prediction in a credit risk portfolio. Collaborative Research Center 386, Discussion Paper 511 [PDF, 407kB]
Czado, Claudia and Song, Peter X.-K. (2006): State space mixed models for longitudinal obsservations with binary and binomial responses. Collaborative Research Center 386, Discussion Paper 503 [PDF, 573kB]
Dargatz, Christiane (2006): A Diffusion Approximation for an Epidemic Model. Collaborative Research Center 386, Discussion Paper 517 [PDF, 842kB]
Fahrmeir, Ludwig and Kneib, Thomas (2006): Propriety of Posteriors in Structured Additive Regression Models: Theory and Empirical Evidence. Collaborative Research Center 386, Discussion Paper 510 [PDF, 949kB]
Fahrmeir, Ludwig and Raach, Alexander (2006): A Bayesian semiparametric latent variable model for mixed responses. Collaborative Research Center 386, Discussion Paper 471 [PDF, 712kB]
Fahrmeir, Ludwig and Steinert, Sven (2006): A geoadditive Bayesian latent variable model for Poisson indicators. Collaborative Research Center 386, Discussion Paper 508 [PDF, 3MB]
Gschlößl, Susanne and Czado, Claudia (2006): Modelling count data with overdispersion and spatial effects. Collaborative Research Center 386, Discussion Paper 475 [PDF, 1MB]
Haug, Stephan and Czado, Claudia (2006): An exponential continuous time GARCH process. Collaborative Research Center 386, Discussion Paper 480 [PDF, 591kB]
Heim, Susanne (2006): Space-Varying Coefficient Models for Diffusion Tensor Imaging using 3d Wavelets. Collaborative Research Center 386, Discussion Paper 505 [PDF, 5MB]
Held, Hermann; Kriegler, Elmar and Augustin, Thomas (2006): Bayesian Learning for a Class of Priors with Prescribed Marginals. Collaborative Research Center 386, Discussion Paper 488 [PDF, 820kB]
Hennerfeind, Andrea and Held, Leonhard (2006): A Bayesian geoadditive relative survival analysis of registry data on breast cancer mortality. Collaborative Research Center 386, Discussion Paper 515 [PDF, 1MB]
Holzmann, Hajo; Min, Aleksey and Czado, Claudia (2006): Validating linear restrictions in linear regression models with general error structure. Collaborative Research Center 386, Discussion Paper 478 [PDF, 407kB]
Högn, Ralph and Czado, Claudia (2006): Multiresolution Analysis of Long Time Series with Applications to Finance. Collaborative Research Center 386, Discussion Paper 497 [PDF, 825kB]
Höhle, Michael (2006): Poisson regression charts for the monitoring of surveillance time series. Collaborative Research Center 386, Discussion Paper 500 [PDF, 397kB]
Höhle, Michael and Held, Leonhard (2006): Bayesian Estimation of the Size of a Population. Collaborative Research Center 386, Discussion Paper 499 [PDF, 618kB]
Klüppelberg, Claudia and Kuhn, Gabriel (2006): Copula Structure Analysis Based on Robust and Extreme Dependence Measures. Collaborative Research Center 386, Discussion Paper 507 [PDF, 393kB]
Klüppelberg, Claudia; Kuhn, Gabriel and Peng, Liang (2006): Estimating Tail Dependence of Elliptical Distributions. Collaborative Research Center 386, Discussion Paper 470 [PDF, 327kB]
Klüppelberg, Claudia; Kuhn, Gabriel and Peng, Liang (2006): Multivariate Tail Copula: Modeling and Estimation. Collaborative Research Center 386, Discussion Paper 468 [PDF, 888kB]
Klüppelberg, Claudia and Peng, Liang (2006): Empirical Likelihodd Methods for an AR(1) process with ARCH(1) errors. Collaborative Research Center 386, Discussion Paper 469 [PDF, 266kB]
Kneib, Thomas; Baumgartner, Bernhard and Steiner, Winfried J. (2006): Semiparametric Multinomial Logit Models for Analysing Consumer Choice Behaviour. Collaborative Research Center 386, Discussion Paper 501 [PDF, 924kB]
Kneib, Thomas and Hennerfeind, Andrea (2006): Bayesian Semiparametric Multi-State Models. Collaborative Research Center 386, Discussion Paper 502 [PDF, 1MB]
Kneib, Thomas; Müller, Jörg and Hothorn, Torsten (2006): Spatial Smoothing Techniques for the Assessment of Habitat Suitability. Collaborative Research Center 386, Discussion Paper 492 [PDF, 800kB]
Krämer, N.; Boulesteix, Anne-Laure and Tutz, Gerhard (2006): Penalized Partial Least Squares Based on B-Splines Transformations. Collaborative Research Center 386, Discussion Paper 485 [PDF, 392kB]
Kukush, Alexander; Malenko, Andrii and Schneeweiß, Hans (2006): Optimality of the quasi-score estimator in a mean-variance model with applications to measurement error models. Collaborative Research Center 386, Discussion Paper 494 [PDF, 327kB]
Kukush, Alexander; Malenko, Andrii; Schneeweiß, Hans and Shalabh (2006): Optimality of Quasi-Score in the multivariate mean-variance model with an application to the zero-inflated Poisson model with measurement errors. Collaborative Research Center 386, Discussion Paper 498 [PDF, 293kB]
Kukush, Alexander and Schneeweiß, Hans (2006): Asymptotic optimality of the quasi-score estimator in a class of linear score estimators. Collaborative Research Center 386, Discussion Paper 477 [PDF, 212kB]
Küchenhoff, Helmut; Lederer, Wolfgang and Lesaffre, Emmanuel (2006): Asymptotic Variance Estimation for the Misclassification SIMEX. Collaborative Research Center 386, Discussion Paper 473 [PDF, 313kB]
Leitenstorfer, Florian and Tutz, Gerhard (2006): Knot selection by boosting techniques. Collaborative Research Center 386, Discussion Paper 481 [PDF, 654kB]
Leitenstorfer, Florian and Tutz, Gerhard (2006): Smoothing with Curvature Constraints based on Boosting Techniques. Collaborative Research Center 386, Discussion Paper 467 [PDF, 319kB]
Müller, Gernot and Czado, Claudia (2006): Stochastic volatility models for ordinal valued time series with application to finance. Collaborative Research Center 386, Discussion Paper 504 [PDF, 417kB]
Neuhaus, Anneke; Augustin, Thomas; Heumann, Christian and Daumer, Martin (2006): A Review on Joint Models in Biometrical Research. Collaborative Research Center 386, Discussion Paper 506 [PDF, 259kB]
Reithinger, Florian; Jank, Wolfgang; Tutz, Gerhard and Shmueli, Galit (2006): Smoothing sparse and unevenly sampled curves using semiparametric mixed models: An application to online auctions. Collaborative Research Center 386, Discussion Paper 483 [PDF, 839kB]
Schmid, Matthias (2006): The Effect of Single-Axis Sorting on the Estimation of a Linear Regression. Collaborative Research Center 386, Discussion Paper 472 [PDF, 290kB]
Schneeweiß, Hans; Komlos, John and Ahmad, A. (2006): Symmetric and Asymmetric Rounding. Collaborative Research Center 386, Discussion Paper 479 [PDF, 473kB]
Schneeweiß, Hans and Kukush, Alexander (2006): Comparing the efficiency of structural and functional methods in measurement error models. Collaborative Research Center 386, Discussion Paper 491 [PDF, 259kB]
Schneeweiß, Hans and Shalabh (2006): On the Estimation of the Linear Relation when the Error Variances are known. Collaborative Research Center 386, Discussion Paper 493 [PDF, 4MB]
Shalabh; Toutenburg, Helge and Heumann, Christian (2006): Performance of Double k-class Estimators for Coefficients in Linear Regression Models with Non Spherical Disturbances under Asymmetric Losses. Collaborative Research Center 386, Discussion Paper 509 [PDF, 241kB]
Shalabh; Toutenburg, Helge and Heumann, Christian (2006): Mean Squared Error Matrix comparison of Least Squares and Stein-Rule Estimators for Regression Coefficients under Non-normal Disturbances. Collaborative Research Center 386, Discussion Paper 496 [PDF, 250kB]
Shalabh; Toutenburg, Helge and Heumann, Christian (2006): Risk Performance Of Stein-Rule Estimators Over The Least Squares Estimators Of Regression Coefficients Under Quadratic Loss Structures. Collaborative Research Center 386, Discussion Paper 495 [PDF, 218kB]
Strobl, Carolin; Boulesteix, Anne-Laure; Zeileis, Achim and Hothorn, Torsten (2006): Bias in Random Forest Variable Importance Measures: Illustrations, Sources and a Solution. Collaborative Research Center 386, Discussion Paper 490 [PDF, 574kB]
Tutz, Gerhard and Ulbricht, Jan (2006): Penalized Regression with Correlation Based Penalty. Collaborative Research Center 386, Discussion Paper 486 [PDF, 472kB]"